### ISSUE TITLE
app crash on 503 error during initialization

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#133]
NOTE: I'm manually moving this report here as it was initially filed against our Express repo: https://github.com/stormpath/stormpath-express/issues/46

For a few minutes, I got the following error during startup of my application.

Stormpath seems to have responded with a 503 status code, which crashed the app.

Meanwhile, everything is working fine again, so I assume that there is an uncaught issue when creating the callback for the request module.

**ERROR**

``` term
/bastian/appxyz/node_modules/express-stormpath/node_modules/stormpath/lib/error/ResourceError.js:7
  this.status = responseBody.status;
                            ^
TypeError: Cannot read property 'status' of undefined
    at new ResourceError (/bastian/appxyz/node_modules/express-stormpath/node_modules/stormpath/lib/error/ResourceError.js:7:29)
    at Request.onRequestResult [as _callback] (/bastian/appxyz/node_modules/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:96:23)
    at Request.self.callback (/bastian/appxyz/node_modules/express-stormpath/node_modules/stormpath/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/bastian/appxyz/node_modules/express-stormpath/node_modules/stormpath/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/bastian/appxyz/node_modules/express-stormpath/node_modules/stormpath/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

**ORIGIN** `stormpath/lib/ds/RequestExectuor.js`

``` javascript
if (response.statusCode > 399) {
      return callback(new ResourceError(body), null);
    }
```

**Comment by jonpaine** [comment]
Giving this a bump. Experiencing identical error on 0.9.1. Of course, I see you guys are having a major outage to handle, which is what's causing this, but it would be nice to prioritize a more graceful failure mode. Thanks!

**Comment by dannytranlx** [comment]
+1

**Comment by rdegges** [comment]
Agreed. I'm working on this with @robertjd on Monday. Sorry for the issues :(

This will be really nice once we get it in there =)

**Comment by jonpaine** [comment]
Not a problem - good luck today!

**Comment by rdegges** [comment]
Thank you! Also, FYI: things are back to normal per our statuspage: http://status.stormpath.com/

**Comment by alavers** [comment]
I guess the chances are slim of this being fixed before the scheduled maintenance downtime tomorrow? :(

**Comment by robertjd** [comment]
Ah!  Looking at this right now..

**Comment by robertjd** [comment]
I just published 0.9.2 which has this change: https://github.com/stormpath/stormpath-sdk-node/commit/dbe131a7a926c599d3df156f932fe00756e25f11

It will give you back an error, and the status will be 503 - I'm considering this a quick fix until we do something more robust like #134

**Comment by alavers** [comment]
Any progress on this? Currently encountering another stormpath outage which is causing our node apps to crash on startup.

**Comment by robertjd** [comment]
It is my understanding that we fixed the problem that was originally mentioned in this post, but I'll investigate how this library handles

* 500 errors from the API
* request timeouts.
