### ISSUE TITLE
Better Error Messages

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#516]
I'm going through our console quickstart for node. The quickstart shows using environment variables to set important application credentials.

If I don't set these variables, and attempt to run the code samples, I get an error that looks like this:

```javascript
/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/ds/RequestExecutor.js:53
    throw new Error('request.uri field is required.');
    ^

Error: request.uri field is required.
    at RequestExecutor.executeRequest [as execute] (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/ds/RequestExecutor.js:53:11)
    at doRequest (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/ds/DataStore.js:272:27)
    at onCacheResult (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/ds/DataStore.js:296:5)
    at Array.<anonymous> (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/cache/Cache.js:54:14)
    at DisabledCache.get.DisabledCache.set.DisabledCache.delete.DisabledCache.clear.DisabledCache.size (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/cache/DisabledCache.js:11:62)
    at Cache.get (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/cache/Cache.js:52:14)
    at CacheHandler.getCachedResource [as get] (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/cache/CacheHandler.js:91:51)
    at Object.executeRequest [as exec] (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/ds/DataStore.js:289:22)
    at DataStore.getResource (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/ds/DataStore.js:117:16)
    at Client.getResource (/Users/rdegges/Dropbox/Code/testing/samples/node_modules/stormpath/lib/Client.js:189:38)
```

This looks pretty nasty. Would be nice to error out better with a usable message.

**Comment by robertjd** [comment]
Can you show me the code you're using?  You should be seeing a nicer message for most cases.

**Comment by rdegges** [comment]
The code from the quickstart in the console. I've just deleted it :( I'm using it verbatim.
